"""Price-time priority limit order book with integer tick prices.

Orders rest in FIFO queues at each price level. A limit order that crosses
the opposite side executes against resting volume, oldest order first,
before any remainder joins the book -- so best_bid() < best_ask() holds
after every operation, not just after non-marketable adds.

Prices are integers (ticks). LOBSTER itself prices in units of 1 / 10000 of a
dollar (see lobster.py); converting to an integer tick index is left to the
caller so this module stays agnostic to the instrument's tick size.
"""

from collections import deque


class Order:
    """A single resting order. Mutated in place by partial fills/cancels."""

    def __init__(self, order_id, side, price, qty):
        if side not in ("bid", "ask"):
            raise ValueError("side must be 'bid' or 'ask', got %r" % (side,))
        if qty <= 0:
            raise ValueError("qty must be positive, got %r" % (qty,))
        self.order_id = order_id
        self.side = side
        self.price = price
        self.qty = qty

    def __repr__(self):
        return "Order(%r, %r, price=%r, qty=%r)" % (
            self.order_id, self.side, self.price, self.qty)


class Fill:
    """One match produced by a market order or a crossing limit order."""

    def __init__(self, price, qty, resting_order_id):
        self.price = price
        self.qty = qty
        self.resting_order_id = resting_order_id

    def __repr__(self):
        return "Fill(price=%r, qty=%r, resting_order_id=%r)" % (
            self.price, self.qty, self.resting_order_id)


class OrderBook:
    """Price-time priority book. One instance per instrument.

    `side` always means the side of the order being submitted, both here and
    in LOBSTER's own `direction` column: "bid" for a buy, "ask" for a sell.
    A market order on the bid side is a buy that consumes resting asks, and
    symmetrically for "ask".
    """

    def __init__(self):
        self.bids = {}      # price -> deque[Order], best = max price
        self.asks = {}       # price -> deque[Order], best = min price
        self._orders = {}    # order_id -> Order, for O(1) cancel lookup

    def best_bid(self):
        return max(self.bids) if self.bids else None

    def best_ask(self):
        return min(self.asks) if self.asks else None

    def _book_for(self, side):
        return self.bids if side == "bid" else self.asks

    def _opposite_for(self, side):
        return self.asks if side == "bid" else self.bids

    def add_limit_order(self, order_id, side, price, qty):
        """Add a limit order, matching against the opposite side first.

        Returns the list of Fills generated by the crossing part, if any (in
        the order they occurred). Any unfilled remainder rests on the book
        at `price`.
        """
        if order_id in self._orders:
            raise ValueError("duplicate order_id %r" % (order_id,))
        if qty <= 0:
            raise ValueError("qty must be positive, got %r" % (qty,))
        opposite = self._opposite_for(side)
        fills = []
        remaining = qty
        while remaining > 0 and opposite:
            best = min(opposite) if side == "bid" else max(opposite)
            crosses = best <= price if side == "bid" else best >= price
            if not crosses:
                break
            remaining = self._consume_level(opposite, best, remaining, fills)
        if remaining > 0:
            order = Order(order_id, side, price, remaining)
            self._book_for(side).setdefault(price, deque()).append(order)
            self._orders[order_id] = order
        return fills

    def market_order(self, side, qty):
        """Walk the opposite side's levels, best price first and FIFO within
        each level, consuming up to `qty`.

        Returns (fills, leftover), where leftover > 0 means the book ran dry
        before `qty` was fully consumed.
        """
        if qty <= 0:
            raise ValueError("qty must be positive, got %r" % (qty,))
        remaining = qty
        opposite = self._opposite_for(side)
        fills = []
        while remaining > 0 and opposite:
            best = min(opposite) if side == "bid" else max(opposite)
            remaining = self._consume_level(opposite, best, remaining, fills)
        return fills, remaining

    def _consume_level(self, opposite, price, remaining, fills):
        """Fill FIFO out of the queue at `price`, appending to `fills`.

        Mutates `opposite` (drops the level once empty) and `self._orders`.
        Returns the quantity still unfilled.
        """
        queue = opposite[price]
        while remaining > 0 and queue:
            resting = queue[0]
            traded = min(remaining, resting.qty)
            fills.append(Fill(price, traded, resting.order_id))
            resting.qty -= traded
            remaining -= traded
            if resting.qty == 0:
                queue.popleft()
                del self._orders[resting.order_id]
        if not queue:
            del opposite[price]
        return remaining

    def cancel_order(self, order_id, qty=None):
        """Cancel all (`qty=None`) or part of a resting order.

        Removes exactly `qty` shares, or the whole order. Raises KeyError if
        `order_id` is not currently resting on the book.
        """
        order = self._orders[order_id]
        book = self._book_for(order.side)
        queue = book[order.price]
        if qty is None or qty >= order.qty:
            queue.remove(order)
            del self._orders[order_id]
            if not queue:
                del book[order.price]
        else:
            if qty <= 0:
                raise ValueError("qty must be positive, got %r" % (qty,))
            order.qty -= qty

    def depth_snapshot(self, n_levels):
        """Top `n_levels` on each side as (price, total_qty), best first."""
        bid_prices = sorted(self.bids, reverse=True)[:n_levels]
        ask_prices = sorted(self.asks)[:n_levels]
        bid_side = [(p, sum(o.qty for o in self.bids[p])) for p in bid_prices]
        ask_side = [(p, sum(o.qty for o in self.asks[p])) for p in ask_prices]
        return bid_side, ask_side
